// src/components/WelcomeScreen.js
import React from 'react';

const WelcomeScreen = ({ onStartGame }) => (
  <div className="absolute inset-0 flex items-center justify-center bg-blue-600 bg-opacity-75 z-40">
    <div className="bg-white p-8 rounded-lg shadow-lg text-center max-w-lg">
      <h1 className="text-3xl font-bold mb-4">Welcome to Earth Explorer!</h1>
      <p className="mb-6">Embark on a geographical adventure around the world. Explore fascinating locations, answer questions generated by AI, and learn interesting facts about our planet.</p>
      <div className="mb-6 bg-blue-50 p-4 rounded">
        <h2 className="font-bold mb-2">How to Play:</h2>
        <ol className="text-left list-decimal pl-5">
          <li className="mb-1">Click on any pin on the globe.</li>
          <li className="mb-1">Answer the geography question provided by our AI explorer.</li>
          <li className="mb-1">Learn interesting facts.</li>
          <li className="mb-1">Complete 10 questions to finish the game.</li>
        </ol>
      </div>
      <button
        className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg text-lg"
        onClick={onStartGame}
      >
        Start Exploring!
      </button>
    </div>
  </div>
);

export default WelcomeScreen;